Document: qpdfview
Title: Debian qpdfview Manual
Author: <insert document author here>
Abstract: This manual describes what qpdfview is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qpdfview/qpdfview.sgml.gz

Format: postscript
Files: /usr/share/doc/qpdfview/qpdfview.ps.gz

Format: text
Files: /usr/share/doc/qpdfview/qpdfview.text.gz

Format: HTML
Index: /usr/share/doc/qpdfview/html/index.html
Files: /usr/share/doc/qpdfview/html/*.html
